name: CD

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  

      - name: hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.80.0' 
          
      - name: build
        run: hugo
        
      - name: deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: .public/
          remote_path: /var/www/html/technically.works/deployed
          remote_host: technically.works
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
